.job_template: &job_definition  # Hidden key that defines an anchor named 'job_definition'
  script:
    - echo "deb http://httpredir.debian.org/debian jessie main" >> /etc/apt/sources.list
    - echo "deb-src http://httpredir.debian.org/debian jessie main" >> /etc/apt/sources.list
    - apt-get update -yy
    - apt-get build-dep -yy python-numpy fftw3
    - apt-get install -yy fftw3-dev libsndfile1 libsndfile1-dev
    - py.test

test:2.7:
  image: python:2.7
  <<: *job_definition

test:3.4:
  image: python:3.4
  <<: *job_definition

test:3.5:
  image: python:3.5
  <<: *job_definition

test:3.6:
  image: python:3.6
  <<: *job_definition
